import React, { useCallback, useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  Image,
} from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { COLORS, RADIUS, SPACING } from '../constants/theme';
import { getHistory } from '../utils/storage';

// Derives pattern insights from pick history
function deriveInsights(history) {
  const count = history.length;
  if (count === 0) return null;

  const posted = history.filter(h => h.posted).length;
  const confidence = count > 0 ? Math.round((posted / count) * 100) : 0;

  // These patterns will eventually be generated by the backend
  // For now, they're surfaced after a threshold of picks
  const patterns = [
    { title: 'You lean clean', body: 'You usually choose the frame with the clearest first read — less noise, more presence.' },
    { title: 'Warm, but controlled', body: "Softer options work best for you when the shape still feels crisp. You don't reach for moody." },
    { title: 'Direct over busy', body: 'You tend toward photos with less visual noise. Strong silhouette beats interesting background.' },
  ];

  return { count, posted, confidence, patterns };
}

export default function StyleScreen({ navigation }) {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);

  useFocusEffect(
    useCallback(() => {
      getHistory().then(h => {
        setHistory(h);
        setLoading(false);
      });
    }, [])
  );

  const insights = deriveInsights(history);
  const recentThumbs = history.slice(0, 6).filter(h => h.thumbnailUri);

  if (!loading && !insights) {
    return (
      <View style={styles.empty}>
        <Text style={styles.emptyTitle}>No patterns yet</Text>
        <Text style={styles.emptyBody}>
          Make a few picks and Pick will start noticing what you keep reaching for.
        </Text>
      </View>
    );
  }

  return (
    <ScrollView
      style={styles.screen}
      contentContainerStyle={styles.content}
      showsVerticalScrollIndicator={false}
    >
      <Text style={styles.title}>Your style</Text>
      <Text style={styles.sub}>
        A running read on what you keep reaching for — built from your picks over time.
      </Text>

      {/* Stats row */}
      {insights && (
        <View style={styles.statsRow}>
          <View style={styles.stat}>
            <Text style={styles.statNum}>{insights.count}</Text>
            <Text style={styles.statLabel}>Total picks</Text>
          </View>
          <View style={styles.stat}>
            <Text style={styles.statNum}>{insights.posted}</Text>
            <Text style={styles.statLabel}>Posted</Text>
          </View>
          <View style={styles.stat}>
            <Text style={styles.statNum}>{insights.confidence}%</Text>
            <Text style={styles.statLabel}>Confidence</Text>
          </View>
        </View>
      )}

      {/* Hero pattern */}
      {insights && (
        <View style={styles.heroCard}>
          <Text style={styles.heroLabel}>Pattern noticed</Text>
          <Text style={styles.heroText}>
            You tend to choose the clearest frame with the strongest first impression.
          </Text>
        </View>
      )}

      {/* Insights */}
      {insights && (
        <>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionLabel}>What works for you</Text>
          </View>
          {insights.patterns.map((insight) => (
            <View key={insight.title} style={styles.insightCard}>
              <Text style={styles.insightTitle}>{insight.title}</Text>
              <Text style={styles.insightBody}>{insight.body}</Text>
            </View>
          ))}
        </>
      )}

      {/* Best picks strip */}
      {recentThumbs.length > 0 && (
        <>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionLabel}>Your best picks</Text>
          </View>
          <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.thumbStrip}>
            {recentThumbs.map((entry, i) => (
              <Image
                key={i}
                source={{ uri: entry.thumbnailUri }}
                style={styles.thumb}
                resizeMode="cover"
              />
            ))}
          </ScrollView>
        </>
      )}

      <View style={{ height: 120 }} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.cream,
  },
  content: {
    paddingHorizontal: SPACING.xl,
    paddingTop: SPACING.xl,
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
    color: COLORS.textPrimary,
    letterSpacing: -0.7,
  },
  sub: {
    marginTop: 6,
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 21,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: SPACING.xl,
  },
  stat: {
    flex: 1,
    backgroundColor: COLORS.surfaceSoft,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.md,
    alignItems: 'center',
  },
  statNum: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.green,
  },
  statLabel: {
    fontSize: 11,
    color: COLORS.textDim,
    marginTop: 3,
    letterSpacing: 0.3,
  },
  heroCard: {
    backgroundColor: COLORS.green,
    borderRadius: RADIUS.lg,
    padding: SPACING.xl,
    marginTop: SPACING.lg,
  },
  heroLabel: {
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 2,
    color: 'rgba(251,244,230,0.6)',
    textTransform: 'uppercase',
  },
  heroText: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.cream,
    letterSpacing: -0.4,
    lineHeight: 24,
  },
  sectionHeader: {
    marginTop: SPACING.xl,
    marginBottom: SPACING.sm,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 2,
    color: COLORS.textDim,
    textTransform: 'uppercase',
  },
  insightCard: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.lg,
    marginTop: SPACING.sm,
  },
  insightTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  insightBody: {
    marginTop: 5,
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  thumbStrip: {
    marginTop: SPACING.sm,
  },
  thumb: {
    width: 80,
    height: 100,
    borderRadius: RADIUS.md,
    marginRight: SPACING.sm,
    backgroundColor: COLORS.surfaceRaised,
  },
  empty: {
    flex: 1,
    backgroundColor: COLORS.cream,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.textPrimary,
    letterSpacing: -0.4,
  },
  emptyBody: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
});
